apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-test.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "helm-test.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: app
  selector:
    app.kubernetes.io/name: {{ include "helm-test.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
